import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { InMemoryFileSystem } from '../fakes/in-memory-file-system.js';
import { FixedClock } from '../fakes/fixed-clock.js';
import { FakeAgentRunner } from '../fakes/fake-agent-runner.js';
import { FakeHost } from '../fakes/fake-host.js';
import { FakeProcessRunner } from '../fakes/fake-process-runner.js';
import { fakeRunActionDeps } from '../fakes/run-action-deps.js';
import { StateStore } from '../../src/app/state-store.js';
import { StageRunner } from '../../src/app/stage-runner.js';
import { PromptLoader } from '../../src/app/prompt-loader.js';
import { TaskExecutor } from '../../src/app/task-executor.js';
import { review } from '../../src/app/run-actions.js';
import { planHash } from '../../src/app/approval.js';
import { runPaths } from '../../src/app/paths.js';
import {
  GlobalConfigSchema,
  PlanSchema,
  ProjectConfigSchema,
  TaskSchema,
  type Amendment,
} from '../../src/contracts/index.js';
import { DEFAULT_GLOBAL_CONFIG_YAML } from '../../src/config/defaults.js';
import type { ProcessSpawnOptions } from '../../src/ports/index.js';

/**
 * NFR-002 — with no operator amendment, the implementation and final-review prompts are
 * the ones `master` sent.
 *
 * **Why fixtures, and why captured first.** The amendments work delivers its text through
 * two existing variables, `failureContext` and `sdd`, so that an empty amendment list
 * changes nothing without touching a template. "Changes nothing" is only provable against
 * what the unchanged tree rendered. A comparison against a render of the edited code proves
 * the code agrees with itself, which it always does. So both fixtures were written once,
 * from the tree before any source change, and this file only reads them: there is no update
 * flag and no environment switch, because a fixture that can be regenerated by the change it
 * guards is a fixture that guards nothing.
 *
 * **Real templates, real renderers.** The implementation prompt goes through the real
 * `TaskExecutor` and `StageRunner` exactly as a sequential run sends it; the final-review
 * prompt goes through `review()` and is read off the stdin of the spawned CLI, which is where
 * the Claude adapter puts it. A stub template would make both comparisons trivially true.
 */

const REAL_PROMPTS = join(import.meta.dirname, '../../prompts');
const FIXTURES = join(import.meta.dirname, '../fixtures/rendered-prompts');

/**
 * The only normalisation, and why it is needed.
 *
 * With `core.autocrlf=true` and no `.gitattributes`, a Windows checkout holds the templates
 * with CRLF, and `prompt-loader` passes the body's `\r\n` through untouched. A Linux checkout
 * holds LF. A byte comparison would then pass on one host and fail on the other for a reason
 * that says nothing about the product. The fixtures are stored LF-only, as JSON strings so
 * that `autocrlf` cannot rewrite them either.
 *
 * Nothing else is normalised: every other input below is fixed by the fakes (`FixedClock`,
 * an in-memory filesystem, a scripted process runner), so no path or duration varies.
 */
function lf(text: string): string {
  return text.replace(/\r\n/g, '\n');
}

function fixture(name: string): string {
  const parsed: unknown = JSON.parse(readFileSync(join(FIXTURES, name), 'utf8'));
  if (typeof parsed !== 'string') throw new Error(`${name} does not hold a JSON string`);
  return parsed;
}

function seedRealPrompts(fs: InMemoryFileSystem, dir: string): void {
  for (const file of readdirSync(REAL_PROMPTS)) {
    if (file.endsWith('.md')) fs.seed(`${dir}/${file}`, readFileSync(join(REAL_PROMPTS, file), 'utf8'));
  }
}

// ---- The implementation prompt ---------------------------------------------------------

const PROJECT = '/repo';

const CAPS = {
  supportedReasoningLevels: ['low', 'medium', 'high', 'very_high'],
  supportsReadOnly: true,
  supportsNonInteractive: true,
  supportsWorkingDirectory: true,
  structuredOutputStrategy: 'native',
  nonInteractiveToolGrants: { fileEdit: true, commandExecution: true },
} as const;

const REPORT = `Done.

## RESULT

STATUS: COMPLETED

FILES CHANGED:
- src/a.ts

DEVIATIONS:
- none

NOTES:
- none
`;

const TASK = TaskSchema.parse({
  id: 'TASK-001',
  title: 'Add the export button',
  description: 'Add a button that exports the current report as CSV.',
  complexity: 'normal',
  risk: 'low',
  dependencies: [],
  requirements: ['FR-001'],
  acceptanceCriteria: ['The button downloads a CSV of the visible rows.'],
  validation: ['test'],
});

const IMPLEMENTATION_SDD = `# Software Design Document

## Functional Requirements

FR-001: The report page offers a CSV export of the rows it shows.
`;

const AGENTS_MD = `# Project Instructions

All source is English. Every behaviour change needs a test.
`;

/** What automatic recovery persists before a retry, exactly as `scheduler.ts` writes it. */
const PACKET = {
  task: 'TASK-001',
  previousAttempt: 1,
  failureClass: 'validation_unsatisfied',
  correctiveObjective: 'The validation the task declares did not pass. Make it pass.',
  acceptanceCriteria: ['The button downloads a CSV of the visible rows.'],
  failedChecks: [
    { command: 'npm test', exitCode: 1, tail: 'AssertionError: expected 2, got 3', truncated: false },
  ],
  successfulChecks: [],
  truncated: [],
};

/** A plan hash the run is approved under. Its value is arbitrary; only equality matters. */
const APPROVED_HASH = 'sha256:approved-plan';

async function renderImplementation(options: {
  failureContext: boolean;
  /** Approve the run under `APPROVED_HASH`, as every answered run is. */
  approved?: boolean;
  /** One `answer` amendment for TASK-001, recorded under `APPROVED_HASH`. */
  answer?: string;
}): Promise<string> {
  const fs = new InMemoryFileSystem();
  const clock = new FixedClock();
  const runner = new FakeAgentRunner('claude', CAPS);
  const prompts = '/pkg/prompts';

  seedRealPrompts(fs, prompts);
  fs.seed(`${PROJECT}/AGENTS.md`, AGENTS_MD);

  const globalConfig = GlobalConfigSchema.parse(parseYaml(DEFAULT_GLOBAL_CONFIG_YAML));
  const store = new StateStore({ fs, clock, projectDir: PROJECT });
  const run = await store.createRun('csv export');

  const executor = new TaskExecutor({
    fs,
    clock,
    store,
    stageRunner: new StageRunner({
      fs,
      clock,
      store,
      config: globalConfig,
      capabilities: { claude: CAPS },
      promptLoader: new PromptLoader({ fs, promptsDir: prompts }),
      getRunner: () => runner,
      projectDir: PROJECT,
    }),
    processRunner: new FakeProcessRunner().always({ exitCode: 0 }),
    config: {
      global: globalConfig,
      project: ProjectConfigSchema.parse({
        project: { name: 'demo', type: 'node' },
        commands: { test: 'npm test' },
      }),
    },
    projectDir: PROJECT,
  });

  runner.pushText(REPORT);

  if (options.approved === true || options.answer !== undefined) {
    const { answer } = options;
    await store.updateRun(run.runId, (state) => ({
      ...state,
      approved: true,
      approvedAt: clock.now(),
      approvedPlanHash: APPROVED_HASH,
      ...(answer === undefined
        ? {}
        : {
            amendments: [
              {
                id: 'AMD-001',
                kind: 'answer' as const,
                actor: { kind: 'keyboard' as const },
                at: clock.now(),
                text: answer,
                task: 'TASK-001',
                planHash: APPROVED_HASH,
              },
            ],
          }),
    }));
  }

  if (options.failureContext) {
    // The only way a failure context reaches this slot: a second attempt with the packet
    // on disk. Sequential mode passes no workspace and so always renders attempt 1.
    fs.seed(runPaths(PROJECT, run.runId).attemptContext('TASK-001', 2), JSON.stringify(PACKET));
    await store.updateRun(run.runId, (state) => ({
      ...state,
      tasks: [{ id: 'TASK-001', state: 'ready' as const, attempts: 1, infrastructureFailures: 0 }],
    }));
    await executor.execute(TASK, run.runId, IMPLEMENTATION_SDD, { path: PROJECT, attempt: 2 });
  } else {
    await store.updateRun(run.runId, (state) => ({
      ...state,
      tasks: [{ id: 'TASK-001', state: 'ready' as const, attempts: 0, infrastructureFailures: 0 }],
    }));
    // No workspace: what the scheduler passes in sequential mode (`prepareWorkspace` returns
    // none when no workspaces are wired), so the attempt is 1 and the failure context empty.
    await executor.execute(TASK, run.runId, IMPLEMENTATION_SDD);
  }

  const prompt = runner.calls.at(-1)?.prompt;
  if (prompt === undefined) throw new Error('the implementation stage never reached the runner');
  return lf(prompt);
}

// ---- The final-review prompt -----------------------------------------------------------

const FINAL_REVIEW_SDD = `# Software Design Document

## Functional Requirements

FR-001: The report page offers a CSV export of the rows it shows.

## Acceptance Criteria

AC-001: The export holds exactly the visible rows.
`;

const PLAN = PlanSchema.parse({
  feature: 'csv-export',
  tasks: [
    {
      id: 'TASK-001',
      title: 'Add the export button',
      description: 'Add a button that exports the current report as CSV.',
      complexity: 'normal',
      risk: 'low',
      dependencies: [],
      requirements: ['FR-001'],
      acceptanceCriteria: ['The button downloads a CSV of the visible rows.'],
      validation: ['test'],
    },
  ],
});

const PROJECT_CONFIG = `project:
  name: demo
  type: node
commands:
  test: npm test
`;

const PASS = { verdict: 'PASS', summary: 'Delivers what was approved.', findings: [] };

async function renderFinalReview(
  sdd: string,
  /** Seeded on the run before `review()`; the time is the fixed clock's. */
  amendments: readonly Omit<Amendment, 'at'>[] = [],
): Promise<string> {
  const fs = new InMemoryFileSystem();
  const clock = new FixedClock();

  fs.seed('/repo/.agent-flow/config.yaml', PROJECT_CONFIG);
  seedRealPrompts(fs, '/install/prompts');

  const store = new StateStore({ fs, clock, projectDir: '/repo' });
  const run = await store.createRun('csv export', () => ({
    isolationMode: 'none' as const,
    workflow: 'standard' as const,
  }));

  await store.writeArtifact(run.runId, 'request', 'Add a CSV export to the report page.\n');
  await store.writeArtifact(run.runId, 'sdd', sdd);
  await store.writeArtifact(run.runId, 'plan', JSON.stringify(PLAN, null, 2));
  await store.updateRun(run.runId, (state) => ({
    ...state,
    status: 'approved',
    approved: true,
    approvedAt: clock.now(),
    approvedPlanHash: planHash(PLAN),
    tasks: [{ id: 'TASK-001', state: 'running', attempts: 1, infrastructureFailures: 0 }],
  }));
  await store.updateRun(run.runId, (state) => ({
    ...state,
    stage: 'implementation',
    tasks: [{ id: 'TASK-001', state: 'completed', attempts: 1, infrastructureFailures: 0 }],
  }));
  if (amendments.length > 0) {
    await store.updateRun(run.runId, (state) => ({
      ...state,
      amendments: amendments.map((amendment) => ({ ...amendment, at: clock.now() })),
    }));
  }

  // The runner that records what it was handed. Git and the validation shell get fixed
  // answers, so `diffStat`, `changedFiles` and `commandResults` are the same on every host.
  const received: string[] = [];
  const processRunner = new FakeProcessRunner().always((opts: ProcessSpawnOptions) => {
    if (opts.command === 'git') {
      // `diffStat()` and `changedFiles()` as a sequential review asks them. The `-z` form of
      // status belongs to the read-only twin, which is left seeing a clean tree.
      if (opts.args.includes('--stat')) {
        return { exitCode: 0, stdout: ' src/export.ts | 12 ++++++++++++\n' };
      }
      if (opts.args.includes('--porcelain=v1') && !opts.args.includes('-z')) {
        return { exitCode: 0, stdout: ' M src/export.ts\n' };
      }
      return { exitCode: 0, stdout: '' };
    }
    if (opts.args.includes('--version')) return { exitCode: 0, stdout: '1.0.0' };
    const stdin = opts.stdin ?? '';
    if (stdin.includes('ROLE: FINAL_REVIEW_AGENT')) received.push(stdin);
    if (opts.args.includes('--json-schema')) {
      return {
        exitCode: 0,
        stdout: JSON.stringify({
          is_error: false,
          subtype: 'success',
          result: JSON.stringify(PASS),
          structured_output: PASS,
        }),
      };
    }
    return { exitCode: 0, stdout: '' };
  });

  const deps = fakeRunActionDeps({
    fs,
    clock,
    processRunner,
    projectDir: '/repo',
    globalConfigPath: '/install/config.yaml',
    promptsDir: '/install/prompts',
    host: new FakeHost(),
    owner: 'cli',
  });

  const outcome = await review(deps, run.runId);
  if (!outcome.ok) throw new Error(`review refused: ${outcome.error.code}`);
  if (received.length !== 1) {
    throw new Error(`expected one final-review prompt, got ${String(received.length)}`);
  }
  return lf(received[0] ?? '');
}

// ---- The comparisons -------------------------------------------------------------------

describe('the implementation prompt, with no amendments, is the one master sent (NFR-002)', () => {
  it('equals the fixture captured from master', async () => {
    expect(await renderImplementation({ failureContext: false })).toBe(
      fixture('implementation.json'),
    );
  });

  it('differs from the fixture once a failure context is present', async () => {
    // POSITIVE CONTROL. The slot the amendments will use is `failureContext`; if filling it
    // left the render equal to the fixture, the comparison above could not see a change.
    const rendered = await renderImplementation({ failureContext: true });

    expect(rendered).toContain('AssertionError: expected 2, got 3');
    expect(rendered).not.toBe(fixture('implementation.json'));
  });

  it('still equals the fixture on an approved run with no amendment', async () => {
    // The answered run below is also an approved one. Without this, the control that follows
    // could be telling approval apart from no approval rather than an answer from none.
    expect(await renderImplementation({ failureContext: false, approved: true })).toBe(
      fixture('implementation.json'),
    );
  });

  it('differs from the fixture once the task has an answer under the approved plan', async () => {
    // POSITIVE CONTROL for the delivery itself (FR-004). The answer reaches the prompt only
    // through the executor reading the run state; if that read were removed, this render
    // would equal the fixture and the equality above would be the only thing left true.
    const rendered = await renderImplementation({
      failureContext: false,
      answer: 'Use the v2 endpoint.',
    });

    expect(rendered).toContain('Use the v2 endpoint.');
    expect(rendered).not.toBe(fixture('implementation.json'));
  });
});

describe('the final-review prompt, with no amendments, is the one master sent (NFR-002)', () => {
  it('equals the fixture captured from master', async () => {
    expect(await renderFinalReview(FINAL_REVIEW_SDD)).toBe(fixture('final-review.json'));
  });

  it('differs from the fixture once the SDD it carries differs', async () => {
    // POSITIVE CONTROL. Amendments reach the final reviewer by extending `sdd`; a different
    // SDD string has to produce a different prompt, or the comparison above proves nothing.
    const changed = `${FINAL_REVIEW_SDD}\n## Operator note\n\nA decision was recorded.\n`;
    const rendered = await renderFinalReview(changed);

    expect(rendered).toContain('A decision was recorded.');
    expect(rendered).not.toBe(fixture('final-review.json'));
  });

  it('differs from the fixture once the run has one amendment (FR-011)', async () => {
    // POSITIVE CONTROL for the delivery itself. The SDD is the fixture's; only the run state
    // differs, so the difference can only come from `judgeRun` reading the amendments.
    const rendered = await renderFinalReview(FINAL_REVIEW_SDD, [
      {
        id: 'AMD-001',
        kind: 'decision',
        actor: { kind: 'keyboard' },
        text: 'Export the visible rows only, never the whole table.',
      },
    ]);

    expect(rendered).toContain('## Operator amendments');
    expect(rendered).toContain('Export the visible rows only, never the whole table.');
    expect(rendered).not.toBe(fixture('final-review.json'));
  });
});

describe('the final-review prompt carries every operator amendment (FR-011)', () => {
  const FINDING = {
    severity: 'medium' as const,
    type: 'test-gap',
    description: 'Nothing tests an empty report (marker-finding).',
    suggestedAction: 'Cover the empty case.',
    evidence: [],
  };

  const AMENDMENTS: readonly Omit<Amendment, 'at'>[] = [
    {
      id: 'AMD-001',
      kind: 'revision',
      actor: { kind: 'keyboard' },
      text: 'Split the button from the serializer (marker-revision).',
    },
    {
      id: 'AMD-002',
      kind: 'escalation',
      actor: { kind: 'device', deviceId: 'dev-1', label: 'tablet' },
      text: 'The export touches every report (marker-escalation).',
      fromWorkflow: 'simple',
      toWorkflow: 'standard',
    },
    {
      id: 'AMD-003',
      kind: 'attached_findings',
      actor: { kind: 'keyboard' },
      planHash: planHash(PLAN),
      findingCount: 1,
      findings: [{ index: 0, finding: FINDING, tasks: ['TASK-001'] }],
    },
    {
      id: 'AMD-004',
      kind: 'answer',
      actor: { kind: 'keyboard' },
      text: 'Use a semicolon as the separator (marker-answer).',
      task: 'TASK-001',
      planHash: planHash(PLAN),
    },
    {
      id: 'AMD-005',
      kind: 'forced_approval',
      actor: { kind: 'keyboard' },
      planHash: planHash(PLAN),
      findingCount: 2,
    },
  ];

  it('lists every amendment, in order, with its kind and its text, after the SDD', async () => {
    const rendered = await renderFinalReview(FINAL_REVIEW_SDD, AMENDMENTS);

    const section = rendered.indexOf('## Operator amendments');
    expect(section).toBeGreaterThan(rendered.indexOf('AC-001: The export holds exactly the visible rows.'));

    let previous = section;
    for (const amendment of AMENDMENTS) {
      const heading = rendered.indexOf(`### ${amendment.id} — ${amendment.kind}`);
      expect(heading, `${amendment.id} is missing`).toBeGreaterThan(previous);
      previous = heading;
      if (amendment.text !== undefined) expect(rendered).toContain(`- Text: ${amendment.text}`);
    }

    // What each kind carries besides its text.
    expect(rendered).toContain('- Actor: tablet');
    expect(rendered).toContain('- Subject: simple → standard');
    expect(rendered).toContain('- Subject: TASK-001');
    expect(rendered).toContain('- Findings in the review: 2');
    expect(rendered).toContain('- Finding 0 (medium, test-gap) → TASK-001: Nothing tests an empty report (marker-finding).');
  });
});
