import { z } from 'zod';

/**
 * Logical reasoning effort (§3.1).
 *
 * These are the only values the core ever sees. Each adapter translates them to
 * whatever its CLI accepts — Claude Code takes `xhigh`, Codex takes something
 * else. Letting a physical value reach the core would defeat the abstraction, so
 * the schema rejects them outright.
 */
export const REASONING_ORDER = ['low', 'medium', 'high', 'very_high'] as const;

export const ReasoningLevelSchema = z.enum(REASONING_ORDER);
export type ReasoningLevel = z.infer<typeof ReasoningLevelSchema>;

/**
 * Logical roles the workflow addresses (§3). Stages resolve roles; they never
 * name a runner or a model.
 */
export const WORKFLOW_ROLES = [
  'architect',
  'sdd',
  'planner',
  'planReviewer',
  'executor.trivial',
  'executor.normal',
  'executor.complex',
  'verification',
  'finalReviewer',
] as const;

export const WorkflowRoleSchema = z.enum(WORKFLOW_ROLES);
export type WorkflowRole = z.infer<typeof WorkflowRoleSchema>;

/**
 * Normalised runner failures (§22.1). Adapters translate their CLI's error
 * vocabulary into these; the core decides on the code and never on the text.
 */
export const RUNNER_ERROR_CODES = [
  'quota_exceeded',
  'auth_required',
  'runner_unavailable',
  'timeout',
  'execution_failed',
  'invalid_output',
  'blocked',
] as const;

export const RunnerErrorCodeSchema = z.enum(RUNNER_ERROR_CODES);
export type RunnerErrorCode = z.infer<typeof RunnerErrorCodeSchema>;

/**
 * The only failures a fallback may react to (§55).
 *
 * Fallback is infrastructure, not a correction strategy. Retrying a poor
 * implementation on a different model buries a quality problem instead of
 * surfacing it, so the remaining codes are deliberately excluded here — at the
 * schema level, where config cannot opt back in.
 */
export const FALLBACK_TRIGGERS = ['quota_exceeded', 'auth_required', 'runner_unavailable'] as const;

export const FallbackTriggerSchema = z.enum(FALLBACK_TRIGGERS);
export type FallbackTrigger = z.infer<typeof FallbackTriggerSchema>;

/** Requirement ids carried by the SDD (§40) and referenced by tasks (§41). */
export const RequirementIdSchema = z
  .string()
  .regex(/^(FR|NFR|SEC)-\d{3}$/, 'expected FR-000, NFR-000 or SEC-000');

export const TaskIdSchema = z.string().regex(/^TASK-\d{3}$/, 'expected TASK-000');

export const FixTaskIdSchema = z.string().regex(/^FIX-\d{3}$/, 'expected FIX-000');

export const AnyTaskIdSchema = z.union([TaskIdSchema, FixTaskIdSchema]);

export const RunIdSchema = z.string().regex(/^AF-\d{4}-\d{3}$/, 'expected AF-YYYY-NNN');

/**
 * A Git object id, lowercase hex, never abbreviated (MVP 2 §5, §10.2).
 *
 * Forty characters because an abbreviation is only unique in the repository that
 * produced it, and only until that repository grows a second object sharing the
 * prefix. Every id recorded through this schema is a claim about one specific
 * commit or tree that a later step re-checks against the repository — and a claim
 * whose meaning can widen is not a claim.
 */
export const CommitOidSchema = z
  .string()
  .regex(/^[0-9a-f]{40}$/, 'expected a 40-character lowercase Git object id');

/**
 * A run's Git namespace: its `runId` plus 64 bits of randomness (MVP 2 §5.2).
 *
 * The suffix exists so a new run cannot adopt the refs of an earlier run with the
 * same id whose state was deleted while its branches were not. The randomness is
 * generated by the application layer at run creation; this schema is the shape
 * everything downstream re-validates against, including immediately before the key
 * is composed into a ref name. That re-validation is the ref-injection defence
 * (§22, S-2), and it must not depend on a caller having done its job.
 */
export const GitRunKeySchema = z
  .string()
  .regex(/^AF-\d{4}-\d{3}-[0-9a-f]{16}$/, 'expected AF-YYYY-NNN-<16 lowercase hex>');

/**
 * Where a run's tasks do their work (MVP 2 §4.4, I-13).
 *
 * Captured once, when the run is created, and immutable afterwards — which is why
 * it is a property of the *run* rather than a question asked of the configuration
 * at each execution. A configuration flag consulted per execution describes the
 * machine at that moment; this describes the run, and a run is the thing the
 * workflow makes promises about.
 *
 * Absent is a third state and not a synonym for `none`: a run created before this
 * field existed predates the question entirely (§25.2), and nothing may promote it.
 */
export const ISOLATION_MODES = ['none', 'worktree'] as const;

export const IsolationModeSchema = z.enum(ISOLATION_MODES);
export type IsolationMode = z.infer<typeof IsolationModeSchema>;

/**
 * Identifier of a validation command declared in the project configuration.
 *
 * The shape is the first of two defences. A plan is written by a model, and the
 * repository's own contents feed the prompt that produces it — so plan content
 * is untrusted input. Before this existed, `Task.validation` was a free string
 * that the orchestrator handed to `/bin/sh -c`, which put model-authored text on
 * a shell *outside* the runner's sandbox, the only containment agent-flow has.
 *
 * Restricting the character set means no string accepted here can express a
 * command, a pipe, a redirect or a substitution. The second defence is
 * `checkPlan`, which requires the id to exist in the project configuration.
 */
export const ValidationIdSchema = z
  .string()
  .regex(
    /^[a-z0-9][a-z0-9-]*$/,
    'expected the id of a validation command declared in the project config ' +
      '(lowercase letters, digits and dashes), not a shell command',
  );

export const IsoTimestampSchema = z.iso.datetime();
