import { spawn, type ChildProcess } from 'node:child_process';
import { createServer } from 'node:net';
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * A real Agent Flow installation, in a directory nobody else can see.
 *
 * The point of this file is what it refuses to fake. A test gets a temp
 * repository, a global configuration, a *built* CLI and a *built* dashboard, and
 * then everything it exercises is production code: `agent-flow ui` binds a real
 * Fastify server, the handlers call the real application services, the services
 * read and write real files. The only thing replaced is the coding CLI itself,
 * through the one seam designed for it — `runners.<id>.command` in the global
 * configuration — so no quota is spent and every answer is identical on every
 * machine.
 *
 * The run directories are not seeded. `agent-flow feature` produces them, which
 * means the plan, its hash, the review that cites that hash and the event trail
 * are all generated by the code under test rather than hand-written into a
 * fixture that can quietly stop matching it.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(HERE, '../../../..');
export const CLI = join(REPO_ROOT, 'dist/bin/agent-flow.js');
const FAKE_CLI = join(HERE, 'fake-agent-cli.mjs');

/** What the fake implementation agent reports. Read by the fake, per process. */
export type ImplOutcome = 'completed' | 'blocked' | 'failed';

export interface WorldOptions {
  /** Which shipped dashboard the real UI server should expose. */
  readonly dashboard?: 'classic' | 'deck';
  /** Directory names under the temp root. Each becomes an Agent Flow project. */
  readonly projects?: readonly string[];
  /** Serve the temp root as a workspace rather than a single project. */
  readonly workspace?: boolean;
  /**
   * Point a role's runner at an executable that does not exist.
   *
   * The honest way to produce `runner_unavailable`: the adapter reports it
   * because the spawn genuinely failed, not because a flag asked it to.
   */
  readonly missingRunner?: 'executors';
  /**
   * Route every role at one runner, so the plan review is not independent.
   *
   * Produces a genuine `single_provider` degradation rather than one written into
   * `state.json` — the run records it because the resolver noticed, which is the
   * only way the warning at the gate can be trusted.
   */
  readonly singleProvider?: boolean;
  /** Command run for the `test` validation id. Must be fast and offline. */
  readonly testCommand?: string;
  /** Skip the planning run, leaving a project with no runs at all. */
  readonly plan?: boolean;
  /**
   * Make each project a real Git repository and ask for worktree isolation.
   *
   * The whole of M2-10's observability is about a run in worktree mode, and a run
   * only *enters* that mode at `createRun`, against a repository that satisfies
   * §6.3 — so there is no way to reach these screens without a real repository
   * with a real commit and a `.gitignore` that ignores Agent Flow's own state.
   * Faking `isolationMode` into `state.json` would be the one thing I-13 exists to
   * make impossible.
   */
  readonly worktrees?: boolean;
  /**
   * Park the implementation agent until the test releases it.
   *
   * The only way to observe a *live* isolated workspace from a browser: the fact
   * is derived from the task being `running` in worktree mode (§21.2), which is a
   * window of milliseconds in a run that is allowed to finish. The fake writes a
   * marker file when it arrives and waits for a release file, so the assertion is
   * driven by evidence on disk rather than by a sleep.
   */
  readonly hold?: boolean;
  /**
   * Park only this task, and let every other agent run to completion.
   *
   * Requires `hold`. A run where every agent waits can only be interrupted before
   * anything reached the integration branch; parking one task in a later wave puts
   * the interruption after some tasks are `completed` and integrated, which is the
   * state §17 recovery actually has to tell apart.
   */
  readonly holdTask?: string;
  /**
   * `parallelism.maxTasks`. Defaults to the shipped 1.
   *
   * What the run *asks* for. What it gets depends on the mode it was born in
   * (§4.4), which is the pair this option exists to exercise.
   */
  readonly maxTasks?: number;
  /**
   * Plan two independent tasks instead of the dependent pair.
   *
   * The default plan has TASK-002 depending on TASK-001, which is right for every
   * scenario about ordering and wrong for every scenario about width: two tasks in
   * a chain can never share a wave, so a parallel run of them is indistinguishable
   * from a sequential one.
   */
  readonly independentTasks?: boolean;
  /**
   * Plan two waves with a fan-in: TASK-001 and TASK-002 independent, TASK-003
   * depending on both, TASK-004 independent of everything.
   *
   * Three tasks ready at once and one that must wait, which is the smallest graph
   * that can be wrong about a wave *base* rather than only about a wave's width.
   * Mutually exclusive with `independentTasks` — they select the same plan slot.
   */
  readonly wavePlan?: boolean;
  /**
   * Check the repository out on this branch before anything is planned.
   *
   * I-10 is a claim about *the user's* checkout, and a repository sitting on the
   * default branch is the one arrangement where "we did not move HEAD" is hardest
   * to distinguish from "there was nowhere else to be".
   */
  readonly branch?: string;
  /**
   * Have every task write the same file, so the second merge conflicts.
   *
   * §15 on screen. Reachable only at a width above one — a conflict is two markers
   * from one wave — which is why the M2-10 read model could describe it before
   * M2-11 could produce one.
   */
  readonly collidingTasks?: boolean;
}

export interface CliResult {
  readonly code: number;
  readonly stdout: string;
  readonly stderr: string;
}

export interface RunnerCall {
  readonly dialect: string;
  readonly role: string;
  readonly argv: string[];
  /**
   * What was under `src/` in the directory this invocation was spawned in.
   *
   * The one observation that distinguishes *which tree* an agent was handed, from
   * outside the process. §19.2's claim is about the reviewer's checkout, and a
   * response body cannot carry it.
   */
  readonly sees?: string[];
}

export class World {
  private disposed = false;

  constructor(
    readonly root: string,
    readonly globalConfigPath: string,
    readonly projectDirs: Readonly<Record<string, string>>,
    readonly fakeLog: string,
    readonly url: string,
    private readonly server: ChildProcess,
    /**
     * What the fake coding CLI is told, whoever spawns it.
     *
     * Held on the world rather than re-derived per call so the server's runners
     * and the CLI's runners cannot be given different instructions — a run
     * started from the browser and one started from a shell have to be the same
     * run, which is the premise every scenario here rests on.
     */
    private readonly fakeEnv: Readonly<Record<string, string>>,
    /** Where the parked agents leave their markers. Absent unless `hold`. */
    readonly holdDir?: string,
  ) {}

  /**
   * Runs `git` in one project and returns its stdout, trimmed.
   *
   * The test's own hand on the repository, deliberately outside the product's
   * `GitCommand`: I-10 says the user's working tree is untouched, and a fingerprint
   * taken through the same client the product uses would be measuring the product
   * with its own ruler.
   */
  async git(project: string, args: readonly string[]): Promise<string> {
    const result = await run('git', ['-C', this.dirOf(project), ...args]);
    if (result.code !== 0) {
      throw new Error(`git ${args.join(' ')} failed: ${result.stderr || result.stdout}`);
    }
    return result.stdout.trim();
  }

  /**
   * Everything about the user's working tree that must be identical afterwards.
   *
   * Four separate questions, because `git status` alone answers none of them
   * conclusively: which commit is checked out, which branch, what the tree looks
   * like including untracked files, and what is staged.
   */
  async workingTree(project: string): Promise<Record<string, string>> {
    return {
      head: await this.git(project, ['rev-parse', 'HEAD']),
      branch: await this.git(project, ['branch', '--show-current']),
      status: await this.git(project, ['status', '--porcelain', '--untracked-files=all']),
      index: await this.git(project, ['ls-files', '--stage']),
    };
  }

  /** Which tasks have a parked agent in them right now. */
  async parked(): Promise<string[]> {
    if (this.holdDir === undefined) return [];
    try {
      const names = await readdir(this.holdDir);
      return names.filter((name) => name.endsWith('.entered')).map((name) => name.slice(0, -8)).sort();
    } catch {
      return [];
    }
  }

  /** Writes a file into a project, as the user would. */
  async writeFile(project: string, relativePath: string, contents: string): Promise<void> {
    await writeFile(join(this.dirOf(project), relativePath), contents, 'utf8');
  }

  /** Lets every parked agent, and every agent that arrives later, through. */
  async release(): Promise<void> {
    if (this.holdDir === undefined) throw new Error('this world was not built with hold');
    await writeFile(join(this.holdDir, 'release'), 'go\n', 'utf8');
  }

  /**
   * Runs the real CLI against one project.
   *
   * Global options go before the subcommand because that is where commander reads
   * them, and `--config` is what keeps every test out of the developer's own
   * `~/.agent-flow`.
   */
  async cli(
    project: string,
    args: readonly string[],
    env: Record<string, string> = {},
  ): Promise<CliResult> {
    const cwd = this.projectDirs[project];
    if (cwd === undefined) throw new Error(`no project "${project}" in this world`);

    return await run(
      process.execPath,
      [CLI, '--cwd', cwd, '--config', this.globalConfigPath, ...args],
      { ...this.fakeEnv, ...env },
    );
  }

  /**
   * The CLI as a process this test still holds, rather than as a promise of its
   * output.
   *
   * §26.5 asks for crashes "driven by killing the coordinator at a deterministic
   * point", and `cli` above cannot be killed — by the time it resolves the run is
   * over. This returns the child so a scenario can `SIGKILL` it while an agent is
   * parked, which is a real crash: no signal handler runs, nothing is flushed,
   * and whatever was half-written stays half-written.
   *
   * `SIGKILL` and not `SIGTERM` on purpose. A terminated process gets to unwind,
   * and a run that unwound tidily is not the state §17 is about.
   */
  spawnCli(project: string, args: readonly string[]): ChildProcess {
    const cwd = this.dirOf(project);
    return spawn(
      process.execPath,
      [CLI, '--cwd', cwd, '--config', this.globalConfigPath, ...args],
      { env: { ...process.env, ...this.fakeEnv }, stdio: ['ignore', 'pipe', 'pipe'], detached: true },
    );
  }

  /** Kills a spawned coordinator and its whole process group, and waits for it. */
  async kill(child: ChildProcess): Promise<void> {
    const exited = new Promise<void>((done) => {
      if (child.exitCode !== null) return done();
      child.once('exit', () => done());
    });
    signal(child, 'SIGKILL');
    await exited;
  }

  dirOf(project: string): string {
    const dir = this.projectDirs[project];
    if (dir === undefined) throw new Error(`no project "${project}" in this world`);
    return dir;
  }

  async runIdOf(project: string): Promise<string> {
    const path = join(this.dirOf(project), '.agent-flow/current-run');
    return (await readFile(path, 'utf8')).trim();
  }

  /**
   * A file under a project directory, or the empty string if it is not there.
   *
   * Absence is an answer rather than a throw, because "this artifact was never
   * written" is a thing scenarios assert on as often as its contents.
   */
  async readProjectFile(project: string, relativePath: string): Promise<string> {
    try {
      return await readFile(join(this.dirOf(project), relativePath), 'utf8');
    } catch {
      return '';
    }
  }

  async stateOf(project: string, runId?: string): Promise<Record<string, unknown>> {
    const id = runId ?? (await this.runIdOf(project));
    const path = join(this.dirOf(project), '.agent-flow/runs', id, 'state.json');
    return JSON.parse(await readFile(path, 'utf8')) as Record<string, unknown>;
  }

  /** Every invocation of the fake CLI so far, oldest first. */
  async runnerCalls(): Promise<RunnerCall[]> {
    try {
      const text = await readFile(this.fakeLog, 'utf8');
      return text
        .split('\n')
        .filter((line) => line.trim().length > 0)
        .map((line) => JSON.parse(line) as RunnerCall);
    } catch {
      // No runner has been invoked yet, which is a normal state to assert on.
      return [];
    }
  }

  async dispose(): Promise<void> {
    if (this.disposed) return;
    this.disposed = true;

    await stop(this.server);
    await rm(this.root, { recursive: true, force: true });
  }
}

export async function createWorld(options: WorldOptions = {}): Promise<World> {
  const names = options.projects ?? ['booking-api'];
  const first = names[0];
  if (first === undefined) throw new Error('a world needs at least one project');

  const root = await mkdtemp(join(tmpdir(), 'agent-flow-e2e-'));
  const fakeLog = join(root, 'runner-calls.jsonl');
  const globalConfigPath = join(root, 'global-config.yaml');
  const projectDirs: Record<string, string> = {};
  let holdDir: string | undefined;

  try {
    await writeFile(globalConfigPath, globalConfig(options), 'utf8');

    if (options.hold === true) {
      holdDir = join(root, 'hold');
      await mkdir(holdDir, { recursive: true });
    }

    // An isolated run gets an agent that genuinely edits its workspace. Without
    // one the attempt's tree equals its base and the integration tree proves
    // nothing about composition; with one, `a.txt` and `b.txt` on the same branch
    // is the whole claim of this milestone.
    const fakeEnv: Record<string, string> = {
      AF_FAKE_LOG: fakeLog,
      SECRET_API_TOKEN: 'resolved-super-secret',
      ...(options.worktrees === true
        ? { AF_FAKE_WRITE: options.collidingTasks === true ? 'shared' : '1' }
        : {}),
      ...(holdDir === undefined ? {} : { AF_FAKE_HOLD: holdDir }),
      ...(holdDir !== undefined && options.holdTask !== undefined
        ? { AF_FAKE_HOLD_TASK: options.holdTask }
        : {}),
      ...(options.wavePlan === true
        ? { AF_FAKE_PLAN: 'wave' }
        : options.independentTasks === true
          ? { AF_FAKE_PLAN: 'independent' }
          : {}),
    };

    for (const name of names) {
      const dir = join(root, name);
      await mkdir(join(dir, '.agent-flow'), { recursive: true });
      await writeFile(
        join(dir, 'package.json'),
        `${JSON.stringify({ name, version: '1.0.0', private: true }, null, 2)}\n`,
        'utf8',
      );
      await writeFile(
        join(dir, '.agent-flow/config.yaml'),
        projectConfig(
          name,
          options.testCommand ?? 'node --version',
          options.worktrees === true,
          options.maxTasks,
        ),
        'utf8',
      );
      projectDirs[name] = dir;

      if (options.worktrees === true) await initRepository(dir, options.branch);
    }

    // Planned before the server starts, by the CLI, so the run the browser opens
    // was produced by the product rather than written into a fixture.
    if (options.plan !== false) {
      for (const name of names) {
        const planned = await run(
          process.execPath,
          [
            CLI,
            '--cwd',
            projectDirs[name] as string,
            '--config',
            globalConfigPath,
            'feature',
            `Add weekly recurrence to ${name}`,
          ],
          fakeEnv,
        );

        if (planned.code !== 0) {
          throw new Error(
            `planning ${name} failed with ${String(planned.code)}\n${planned.stdout}\n${planned.stderr}`,
          );
        }
      }
    }

    const served = options.workspace === true ? root : (projectDirs[first] as string);
    const { child, url } = await startServer(
      globalConfigPath,
      served,
      root,
      fakeEnv,
      options.dashboard ?? 'classic',
    );

    return new World(
      root,
      globalConfigPath,
      projectDirs,
      fakeLog,
      url,
      child,
      fakeEnv,
      ...(holdDir === undefined ? [] : ([holdDir] as const)),
    );
  } catch (error) {
    await rm(root, { recursive: true, force: true });
    throw error;
  }
}

// ---------------------------------------------------------------------------

/**
 * A repository the §6.3 preconditions accept.
 *
 * Four of them are load-bearing here and each one is a real failure mode rather
 * than ceremony: there has to be a commit (`repository_has_no_commits`); the
 * working tree has to be clean, so everything written above is committed
 * (`working_tree_dirty`); Agent Flow's own run state has to be ignored, or the
 * run refuses itself over files it just wrote (`agent_flow_state_not_ignored`);
 * and the identity comes from a local `user.email`, so the machine's own Git
 * configuration cannot make the test pass or fail.
 */
async function initRepository(dir: string, branch: string | undefined): Promise<void> {
  await writeFile(
    join(dir, '.gitignore'),
    '.agent-flow/runs/\n.agent-flow/cache/\n.agent-flow/current-run\n',
    'utf8',
  );

  const steps: readonly (readonly string[])[] = [
    ['init', '--initial-branch=main'],
    ['config', 'user.email', 'e2e@agent-flow.test'],
    ['config', 'user.name', 'Agent Flow E2E'],
    ['config', 'commit.gpgsign', 'false'],
    ['add', '--all'],
    ['commit', '--message', 'initial commit'],
    // After the commit, so the branch has a tip. `checkout -b` on an unborn HEAD
    // would leave the repository with no commits, which §6.3 check 3 refuses.
    ...(branch === undefined ? [] : [['checkout', '-b', branch]]),
  ];

  for (const args of steps) {
    const result = await run('git', ['-C', dir, ...args]);
    if (result.code !== 0) {
      throw new Error(`git ${args.join(' ')} failed in ${dir}: ${result.stderr || result.stdout}`);
    }
  }
}

async function startServer(
  globalConfigPath: string,
  served: string,
  cwd: string,
  fakeEnv: Readonly<Record<string, string>>,
  dashboard: 'classic' | 'deck',
): Promise<{ child: ChildProcess; url: string }> {
  const port = await freePort();

  const child = spawn(
    process.execPath,
    [
      CLI,
      '--config',
      globalConfigPath,
      'ui',
      served,
      '--port',
      String(port),
      '--no-open',
      ...(dashboard === 'classic' ? ['--classic'] : []),
    ],
    {
      cwd,
      env: { ...process.env, ...fakeEnv },
      stdio: ['ignore', 'pipe', 'pipe'],
      // Its own process group, so teardown can take the runner children with it.
      detached: process.platform !== 'win32',
    },
  );

  let output = '';
  for (const stream of [child.stdout, child.stderr]) {
    stream?.setEncoding('utf8');
    stream?.on('data', (chunk: string) => {
      output += chunk;
    });
  }

  const url = `http://127.0.0.1:${String(port)}`;
  if (!(await waitForHealth(url, child))) {
    await stop(child);
    throw new Error(`agent-flow ui never answered on ${url}\n${output}`);
  }

  return { child, url };
}

function globalConfig(options: WorldOptions): string {
  // A distinct id rather than a broken command on `codex`, so only the role
  // pointed at it is affected and the rest of the run still behaves.
  const absent = '/nonexistent/agent-flow-e2e-no-such-runner';
  const planner = options.singleProvider === true ? 'claude' : 'codex';
  const executor =
    options.missingRunner === 'executors' ? 'broken' : options.singleProvider === true ? 'claude' : 'codex';

  // `enabled: true` is not redundant. The shipped defaults enable one runner out
  // of the box, and a config that omits the flag inherits that — so the second
  // runner was declared, disabled, and every cross-provider role refused to
  // resolve.
  return `version: 1
runners:
  claude:
    type: claude-code-cli
    enabled: true
    command: ${FAKE_CLI}
    apiKeyEnv: SECRET_API_TOKEN
  codex:
    type: codex-cli
    enabled: true
    command: ${FAKE_CLI}
  broken:
    type: codex-cli
    enabled: true
    command: ${absent}
roles:
  architect:     { runner: claude, effort: high }
  sdd:           { runner: claude, effort: high }
  planner:       { runner: ${planner}, effort: high }
  planReviewer:  { runner: claude, effort: high }
  executors:
    trivial:     { runner: ${executor}, effort: low }
    normal:      { runner: ${executor}, effort: medium }
    complex:     { runner: ${executor}, effort: high }
  verification:  { runner: ${planner}, effort: medium }
  finalReviewer: { runner: claude, effort: very_high }
fallback:
  enabled: false
ui:
  workspaceDepth: 2
unknownFixture:
  privateValue: unknown-secret-value
`;
}

/**
 * The versioned project file, written rather than produced by `init`.
 *
 * A fixture repository has one committed, and writing it here keeps the
 * validation command under the test's control: `node --version` exits zero in
 * milliseconds, offline, on every platform.
 */
function projectConfig(
  name: string,
  testCommand: string,
  worktrees: boolean,
  maxTasks: number | undefined,
): string {
  // `git` and `parallelism` are both project-overridable keys, so the repository
  // states what makes it different and the global file stays the shipped default —
  // which is also what keeps two projects in one workspace independent.
  return `project:
  name: ${name}
  type: node
commands:
  test: ${testCommand}
${worktrees ? 'git:\n  useWorktrees: true\n' : ''}${
    maxTasks === undefined ? '' : `parallelism:\n  maxTasks: ${String(maxTasks)}\n`
  }`;
}

async function waitForHealth(url: string, child: ChildProcess): Promise<boolean> {
  const deadline = Date.now() + 30_000;

  while (Date.now() < deadline) {
    // A server that died is not a server that is slow. Without this the wait
    // reports a timeout and hides the reason it never started.
    if (child.exitCode !== null) return false;

    try {
      if ((await fetch(`${url}/api/v1/health`)).ok) return true;
    } catch {
      // Not listening yet.
    }
    await sleep(100);
  }

  return false;
}

async function stop(child: ChildProcess): Promise<void> {
  if (child.exitCode !== null || child.pid === undefined) return;

  const exited = new Promise<void>((done) => {
    child.once('exit', () => done());
    const guard = setTimeout(done, 5_000);
    guard.unref?.();
  });

  signal(child, 'SIGTERM');
  await exited;
  // Anything left in the group after the grace period. A runner child holding the
  // port is what makes the *next* test fail, which is the worst place to find out.
  signal(child, 'SIGKILL');
}

function signal(child: ChildProcess, sig: NodeJS.Signals): void {
  try {
    if (process.platform !== 'win32' && child.pid !== undefined) process.kill(-child.pid, sig);
    else child.kill(sig);
  } catch {
    // Already gone, or never started.
  }
}

/**
 * A port the operating system says is free, right now.
 *
 * Deliberately not "base + worker index": two suites running at once, or a
 * leftover process from a cancelled run, both turn a computed port into a flake
 * that looks like a product bug. Asking for port 0 and reading back what was
 * granted is the only answer that cannot collide.
 */
function freePort(): Promise<number> {
  return new Promise((done, fail) => {
    const probe = createServer();
    probe.unref();
    probe.on('error', fail);
    probe.listen(0, '127.0.0.1', () => {
      const address = probe.address();
      const port = typeof address === 'object' && address !== null ? address.port : 0;
      probe.close(() => {
        if (port === 0) fail(new Error('could not obtain a free port'));
        else done(port);
      });
    });
  });
}

function run(
  command: string,
  args: readonly string[],
  env: Record<string, string> = {},
): Promise<CliResult> {
  return new Promise((done) => {
    const child = spawn(command, [...args], {
      env: { ...process.env, ...env },
      stdio: ['ignore', 'pipe', 'pipe'],
    });

    let stdout = '';
    let stderr = '';
    child.stdout?.setEncoding('utf8');
    child.stderr?.setEncoding('utf8');
    child.stdout?.on('data', (chunk: string) => {
      stdout += chunk;
    });
    child.stderr?.on('data', (chunk: string) => {
      stderr += chunk;
    });
    child.on('close', (code) => done({ code: code ?? -1, stdout, stderr }));
  });
}

function sleep(ms: number): Promise<void> {
  return new Promise((done) => {
    const timer = setTimeout(done, ms);
    timer.unref?.();
  });
}
