import { spawn, type ChildProcess } from 'node:child_process';
import { createServer } from 'node:net';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * A real Agent Flow installation, in a directory nobody else can see.
 *
 * The point of this file is what it refuses to fake. A test gets a temp
 * repository, a global configuration, a *built* CLI and a *built* dashboard, and
 * then everything it exercises is production code: `agent-flow ui` binds a real
 * Fastify server, the handlers call the real application services, the services
 * read and write real files. The only thing replaced is the coding CLI itself,
 * through the one seam designed for it — `runners.<id>.command` in the global
 * configuration — so no quota is spent and every answer is identical on every
 * machine.
 *
 * The run directories are not seeded. `agent-flow feature` produces them, which
 * means the plan, its hash, the review that cites that hash and the event trail
 * are all generated by the code under test rather than hand-written into a
 * fixture that can quietly stop matching it.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(HERE, '../../../..');
export const CLI = join(REPO_ROOT, 'dist/bin/agent-flow.js');
const FAKE_CLI = join(HERE, 'fake-agent-cli.mjs');

/** What the fake implementation agent reports. Read by the fake, per process. */
export type ImplOutcome = 'completed' | 'blocked' | 'failed';

export interface WorldOptions {
  /** Directory names under the temp root. Each becomes an Agent Flow project. */
  readonly projects?: readonly string[];
  /** Serve the temp root as a workspace rather than a single project. */
  readonly workspace?: boolean;
  /**
   * Point a role's runner at an executable that does not exist.
   *
   * The honest way to produce `runner_unavailable`: the adapter reports it
   * because the spawn genuinely failed, not because a flag asked it to.
   */
  readonly missingRunner?: 'executors';
  /**
   * Route every role at one runner, so the plan review is not independent.
   *
   * Produces a genuine `single_provider` degradation rather than one written into
   * `state.json` — the run records it because the resolver noticed, which is the
   * only way the warning at the gate can be trusted.
   */
  readonly singleProvider?: boolean;
  /** Command run for the `test` validation id. Must be fast and offline. */
  readonly testCommand?: string;
  /** Skip the planning run, leaving a project with no runs at all. */
  readonly plan?: boolean;
}

export interface CliResult {
  readonly code: number;
  readonly stdout: string;
  readonly stderr: string;
}

export interface RunnerCall {
  readonly dialect: string;
  readonly role: string;
  readonly argv: string[];
}

export class World {
  private disposed = false;

  constructor(
    readonly root: string,
    readonly globalConfigPath: string,
    readonly projectDirs: Readonly<Record<string, string>>,
    readonly fakeLog: string,
    readonly url: string,
    private readonly server: ChildProcess,
  ) {}

  /**
   * Runs the real CLI against one project.
   *
   * Global options go before the subcommand because that is where commander reads
   * them, and `--config` is what keeps every test out of the developer's own
   * `~/.agent-flow`.
   */
  async cli(
    project: string,
    args: readonly string[],
    env: Record<string, string> = {},
  ): Promise<CliResult> {
    const cwd = this.projectDirs[project];
    if (cwd === undefined) throw new Error(`no project "${project}" in this world`);

    return await run(
      process.execPath,
      [CLI, '--cwd', cwd, '--config', this.globalConfigPath, ...args],
      { AF_FAKE_LOG: this.fakeLog, ...env },
    );
  }

  dirOf(project: string): string {
    const dir = this.projectDirs[project];
    if (dir === undefined) throw new Error(`no project "${project}" in this world`);
    return dir;
  }

  async runIdOf(project: string): Promise<string> {
    const path = join(this.dirOf(project), '.agent-flow/current-run');
    return (await readFile(path, 'utf8')).trim();
  }

  async stateOf(project: string, runId?: string): Promise<Record<string, unknown>> {
    const id = runId ?? (await this.runIdOf(project));
    const path = join(this.dirOf(project), '.agent-flow/runs', id, 'state.json');
    return JSON.parse(await readFile(path, 'utf8')) as Record<string, unknown>;
  }

  /** Every invocation of the fake CLI so far, oldest first. */
  async runnerCalls(): Promise<RunnerCall[]> {
    try {
      const text = await readFile(this.fakeLog, 'utf8');
      return text
        .split('\n')
        .filter((line) => line.trim().length > 0)
        .map((line) => JSON.parse(line) as RunnerCall);
    } catch {
      // No runner has been invoked yet, which is a normal state to assert on.
      return [];
    }
  }

  async dispose(): Promise<void> {
    if (this.disposed) return;
    this.disposed = true;

    await stop(this.server);
    await rm(this.root, { recursive: true, force: true });
  }
}

export async function createWorld(options: WorldOptions = {}): Promise<World> {
  const names = options.projects ?? ['booking-api'];
  const first = names[0];
  if (first === undefined) throw new Error('a world needs at least one project');

  const root = await mkdtemp(join(tmpdir(), 'agent-flow-e2e-'));
  const fakeLog = join(root, 'runner-calls.jsonl');
  const globalConfigPath = join(root, 'global-config.yaml');
  const projectDirs: Record<string, string> = {};

  try {
    await writeFile(globalConfigPath, globalConfig(options), 'utf8');

    for (const name of names) {
      const dir = join(root, name);
      await mkdir(join(dir, '.agent-flow'), { recursive: true });
      await writeFile(
        join(dir, 'package.json'),
        `${JSON.stringify({ name, version: '1.0.0', private: true }, null, 2)}\n`,
        'utf8',
      );
      await writeFile(
        join(dir, '.agent-flow/config.yaml'),
        projectConfig(name, options.testCommand ?? 'node --version'),
        'utf8',
      );
      projectDirs[name] = dir;
    }

    // Planned before the server starts, by the CLI, so the run the browser opens
    // was produced by the product rather than written into a fixture.
    if (options.plan !== false) {
      for (const name of names) {
        const planned = await run(
          process.execPath,
          [
            CLI,
            '--cwd',
            projectDirs[name] as string,
            '--config',
            globalConfigPath,
            'feature',
            `Add weekly recurrence to ${name}`,
          ],
          { AF_FAKE_LOG: fakeLog },
        );

        if (planned.code !== 0) {
          throw new Error(
            `planning ${name} failed with ${String(planned.code)}\n${planned.stdout}\n${planned.stderr}`,
          );
        }
      }
    }

    const served = options.workspace === true ? root : (projectDirs[first] as string);
    const { child, url } = await startServer(globalConfigPath, served, root, fakeLog);

    return new World(root, globalConfigPath, projectDirs, fakeLog, url, child);
  } catch (error) {
    await rm(root, { recursive: true, force: true });
    throw error;
  }
}

// ---------------------------------------------------------------------------

async function startServer(
  globalConfigPath: string,
  served: string,
  cwd: string,
  fakeLog: string,
): Promise<{ child: ChildProcess; url: string }> {
  const port = await freePort();

  const child = spawn(
    process.execPath,
    [CLI, '--config', globalConfigPath, 'ui', served, '--port', String(port), '--no-open'],
    {
      cwd,
      env: { ...process.env, AF_FAKE_LOG: fakeLog },
      stdio: ['ignore', 'pipe', 'pipe'],
      // Its own process group, so teardown can take the runner children with it.
      detached: process.platform !== 'win32',
    },
  );

  let output = '';
  for (const stream of [child.stdout, child.stderr]) {
    stream?.setEncoding('utf8');
    stream?.on('data', (chunk: string) => {
      output += chunk;
    });
  }

  const url = `http://127.0.0.1:${String(port)}`;
  if (!(await waitForHealth(url, child))) {
    await stop(child);
    throw new Error(`agent-flow ui never answered on ${url}\n${output}`);
  }

  return { child, url };
}

function globalConfig(options: WorldOptions): string {
  // A distinct id rather than a broken command on `codex`, so only the role
  // pointed at it is affected and the rest of the run still behaves.
  const absent = '/nonexistent/agent-flow-e2e-no-such-runner';
  const planner = options.singleProvider === true ? 'claude' : 'codex';
  const executor =
    options.missingRunner === 'executors' ? 'broken' : options.singleProvider === true ? 'claude' : 'codex';

  // `enabled: true` is not redundant. The shipped defaults enable one runner out
  // of the box, and a config that omits the flag inherits that — so the second
  // runner was declared, disabled, and every cross-provider role refused to
  // resolve.
  return `version: 1
runners:
  claude:
    type: claude-code-cli
    enabled: true
    command: ${FAKE_CLI}
  codex:
    type: codex-cli
    enabled: true
    command: ${FAKE_CLI}
  broken:
    type: codex-cli
    enabled: true
    command: ${absent}
roles:
  architect:     { runner: claude, effort: high }
  sdd:           { runner: claude, effort: high }
  planner:       { runner: ${planner}, effort: high }
  planReviewer:  { runner: claude, effort: high }
  executors:
    trivial:     { runner: ${executor}, effort: low }
    normal:      { runner: ${executor}, effort: medium }
    complex:     { runner: ${executor}, effort: high }
  verification:  { runner: ${planner}, effort: medium }
  finalReviewer: { runner: claude, effort: very_high }
fallback:
  enabled: false
ui:
  workspaceDepth: 2
`;
}

/**
 * The versioned project file, written rather than produced by `init`.
 *
 * A fixture repository has one committed, and writing it here keeps the
 * validation command under the test's control: `node --version` exits zero in
 * milliseconds, offline, on every platform.
 */
function projectConfig(name: string, testCommand: string): string {
  return `project:
  name: ${name}
  type: node
commands:
  test: ${testCommand}
`;
}

async function waitForHealth(url: string, child: ChildProcess): Promise<boolean> {
  const deadline = Date.now() + 30_000;

  while (Date.now() < deadline) {
    // A server that died is not a server that is slow. Without this the wait
    // reports a timeout and hides the reason it never started.
    if (child.exitCode !== null) return false;

    try {
      if ((await fetch(`${url}/api/v1/health`)).ok) return true;
    } catch {
      // Not listening yet.
    }
    await sleep(100);
  }

  return false;
}

async function stop(child: ChildProcess): Promise<void> {
  if (child.exitCode !== null || child.pid === undefined) return;

  const exited = new Promise<void>((done) => {
    child.once('exit', () => done());
    const guard = setTimeout(done, 5_000);
    guard.unref?.();
  });

  signal(child, 'SIGTERM');
  await exited;
  // Anything left in the group after the grace period. A runner child holding the
  // port is what makes the *next* test fail, which is the worst place to find out.
  signal(child, 'SIGKILL');
}

function signal(child: ChildProcess, sig: NodeJS.Signals): void {
  try {
    if (process.platform !== 'win32' && child.pid !== undefined) process.kill(-child.pid, sig);
    else child.kill(sig);
  } catch {
    // Already gone, or never started.
  }
}

/**
 * A port the operating system says is free, right now.
 *
 * Deliberately not "base + worker index": two suites running at once, or a
 * leftover process from a cancelled run, both turn a computed port into a flake
 * that looks like a product bug. Asking for port 0 and reading back what was
 * granted is the only answer that cannot collide.
 */
function freePort(): Promise<number> {
  return new Promise((done, fail) => {
    const probe = createServer();
    probe.unref();
    probe.on('error', fail);
    probe.listen(0, '127.0.0.1', () => {
      const address = probe.address();
      const port = typeof address === 'object' && address !== null ? address.port : 0;
      probe.close(() => {
        if (port === 0) fail(new Error('could not obtain a free port'));
        else done(port);
      });
    });
  });
}

function run(
  command: string,
  args: readonly string[],
  env: Record<string, string> = {},
): Promise<CliResult> {
  return new Promise((done) => {
    const child = spawn(command, [...args], {
      env: { ...process.env, ...env },
      stdio: ['ignore', 'pipe', 'pipe'],
    });

    let stdout = '';
    let stderr = '';
    child.stdout?.setEncoding('utf8');
    child.stderr?.setEncoding('utf8');
    child.stdout?.on('data', (chunk: string) => {
      stdout += chunk;
    });
    child.stderr?.on('data', (chunk: string) => {
      stderr += chunk;
    });
    child.on('close', (code) => done({ code: code ?? -1, stdout, stderr }));
  });
}

function sleep(ms: number): Promise<void> {
  return new Promise((done) => {
    const timer = setTimeout(done, ms);
    timer.unref?.();
  });
}
